### ISSUE TITLE
Unhandled characters in build info args

### ISSUE THREAD

**Issue by MSeba1** [camden-smallwood/pdb-decompiler#17]
Hello, im getting a weird error, something about MultipleProcessSupport flag?
here is the log

```
0x180000000`
thread 'main' panicked at src/cpp/module.rs:873:36:
Unhandled characters in build info arg: 'MP1...'
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

Im running the script on ubuntu 22.04 and rustc 1.74.0

**Comment by MSeba1** [comment]
even if i try avoid getting panicked, another error comes up
`Unhandled characters in build info arg: 'O14...'
`

**Comment by camden-smallwood** [comment]
Hey there, I've implemented a fix for `/MP` compiler options in commit [9b61f77](https://github.com/camden-smallwood/pdb-decompiler/commit/9b61f77ef763e93b18a87fe2042bb931c3d759f9), which should resolve your first issue. The second issue seems a little odd, does it still happen after the aforementioned fix? If so, is this PDB file publicly available so that I can debug it locally? The `/O14` flag isn't documented, which you can see here: https://learn.microsoft.com/en-us/cpp/build/reference/o-options-optimize-code?view=msvc-170

**Comment by MSeba1** [comment]
Hello, first of all thanks for the fast response, you are right after fixing the first error now i get a different one
`not yet implemented: arg switch 'Zf...'
`
please ignore /O14 not sure how i got that error
unfortunately the pdf is not public

**Comment by camden-smallwood** [comment]
No problem, if you don't mind reporting on any missing build info arg support in here, then I'll do what I can to get them implemented. I have added support for the `/Zf` option in commit [521a802](https://github.com/camden-smallwood/pdb-decompiler/commit/521a80246482ffce0431f33addce6419152890e1).

**Comment by MSeba1** [comment]
sure, gotta catch them all i guess?
next one is 
`Unhandled characters in build info arg: 'experimental'
`

**Comment by MSeba1** [comment]
ok, next one
`Unhandled characters in build info arg: 'experimental:deterministic'
`

**Comment by camden-smallwood** [comment]
OK that one should be fixed with commit [86a5d79](https://github.com/camden-smallwood/pdb-decompiler/commit/86a5d798e0c35084314b8c59cb4e7e53f6783ff4).

**Comment by MSeba1** [comment]
next
`Unhandled characters in build info arg: 'GR-3...'
`

**Comment by camden-smallwood** [comment]
That's a strange one because it doesn't seem to follow the documentation of the `/GR` option as specified here: https://learn.microsoft.com/en-us/cpp/build/reference/gr-enable-run-time-type-information?view=msvc-160

I've made a change that includes the build info args when an unexpected character is encountered in commit [2ff0ba3](https://github.com/camden-smallwood/pdb-decompiler/commit/2ff0ba37cda1f3910cf6f75d89fdafed1c413b49). Could you include the entire new error message so that I can verify the context and ensure it's not a parsing error?

**Comment by MSeba1** [comment]
the full error is like the others
```
thread 'main' panicked at src/cpp/module.rs:825:40:
Unhandled characters in build info arg: 'GR-3...'
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by camden-smallwood** [comment]
I think your local copy might be out of date. Could you verify that your `src/cpp/module.rs` has the same message string as the repository's at line 825? https://github.com/camden-smallwood/pdb-decompiler/blob/main/src/cpp/module.rs#L825

**Comment by MSeba1** [comment]
do you have telegram? i found the GR-3 issue i think

**Comment by camden-smallwood** [comment]
Yes I do, my account is `@camdensmallwood`

**Comment by Tamashh** [comment]
i seem to be having a similair issue but with source-charset:utf-8 here is the log:
`Running `target/release/pdb-decompiler --out=outp --pdb=fnaf9-Win64-Shipping.pdb`
thread 'main' panicked at 'Unhandled characters in build info arg: 'source-charset:utf-8'; Data: "-Zc:inline -nologo -Oi -c -Gw -Gy -Zm1000 -wd4819 -D_CRT_STDIO_LEGACY_WIDE_SPECIFIERS=1 -D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS=1 -D_DISABLE_EXTENDED_ALIGNED_STORAGE -source-charset:utf-8 -execution-charset:utf-8 -Ob2 -Ox -Ot -GF -errorreport:prompt -D_HAS_EXCEPTIONS=0 -Z7 -MD -bigobj -fp:fast -Zo -Zp8 -we4456 -we4458 -we4459 -wd4463 -we4668 -wd4244 -wd4838 -ID:\BuildAgent\work\FNAF9\Engine\Source -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\Launch\Private -ID:\BuildAgent\work\FNAF9\Engine\Source\Developer\DerivedDataCache\Public -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\TraceLog\Public -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\Core\Public -ID:\BuildAgent\work\FNAF9\fnaf9\Intermediate\Build\Win64\fnaf9\Inc\CoreUObject -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\CoreUObject\Public -ID:\BuildAgent\work\FNAF9\fnaf9\Intermediate\Build\Win64\fnaf9\Inc\Engine -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\Engine\Classes -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\Engine\Public -ID:\BuildAgent\work\FNAF9\fnaf9\Intermediate\Build\Win64\fnaf9\Inc\NetCore -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\Net -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\Net\Core\Classes -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\Net\Core\Public -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\ApplicationCore\Public -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\RHI\Public -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\Json\Public -ID:\BuildAgent\work\FNAF9\fnaf9\Intermediate\Build\Win64\fnaf9\Inc\SlateCore -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\SlateCore\Public -ID:\BuildAgent\work\FNAF9\fnaf9\Intermediate\Build\Win64\fnaf9\Inc\InputCore -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\InputCore\Classes -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\InputCore\Public -ID:\BuildAgent\work\FNAF9\fnaf9\Intermediate\Build\Win64\fnaf9\Inc\Slate -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\Slate\Public -ID:\BuildAgent\work\FNAF9\fnaf9\Intermediate\Build\Win64\fnaf9\Inc\ImageWrapper -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\ImageWrapper\Public -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\Messaging\Public -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\MessagingCommon\Public -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\RenderCore\Public -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\Analytics -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\Analytics\AnalyticsET\Public -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\Analytics\Analytics\Public -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\Sockets\Public -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\Net\Common\Public -ID:\BuildAgent\work\FNAF9\fnaf9\Intermediate\Build\Win64\fnaf9\Inc\AssetRegistry -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\AssetRegistry\Public -ID:\BuildAgent\work\FNAF9\fnaf9\Intermediate\Build\Win64\fnaf9\Inc\EngineMessages -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\EngineMessages\Public -ID:\BuildAgent\work\FNAF9\fnaf9\Intermediate\Build\Win64\fnaf9\Inc\EngineSettings -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\EngineSettings\Classes -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\EngineSettings\Public -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\SynthBenchmark\Public -ID:\BuildAgent\work\FNAF9\fnaf9\Intermediate\Build\Win64\fnaf9\Inc\Renderer -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\Renderer\Public -ID:\BuildAgent\work\FNAF9\fnaf9\Intermediate\Build\Win64\fnaf9\Inc\GameplayTags -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\GameplayTags\Classes -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\GameplayTags\Public -ID:\BuildAgent\work\FNAF9\fnaf9\Intermediate\Build\Win64\fnaf9\Inc\DeveloperSettings -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\DeveloperSettings\Public -ID:\BuildAgent\work\FNAF9\fnaf9\Intermediate\Build\Win64\fnaf9\Inc\PacketHandler -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\PacketHandlers -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\PacketHandlers\PacketHandler\Classes -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\PacketHandlers\PacketHandler\Public -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\PacketHandlers\ReliabilityHandlerComponent\Public -ID:\BuildAgent\work\FNAF9\fnaf9\Intermediate\Build\Win64\fnaf9\Inc\AudioPlatformConfiguration -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\AudioPlatformConfiguration\Public -ID:\BuildAgent\work\FNAF9\fnaf9\Intermediate\Build\Win64\fnaf9\Inc\MeshDescription -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\MeshDescription\Public -ID:\BuildAgent\work\FNAF9\fnaf9\Intermediate\Build\Win64\fnaf9\Inc\StaticMeshDescription -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\StaticMeshDescription\Public -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\PakFile\Public -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\RSA\Public -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\NetworkReplayStreaming -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\NetworkReplayStreaming\NetworkReplayStreaming\Public -ID:\BuildAgent\work\FNAF9\fnaf9\Intermediate\Build\Win64\fnaf9\Inc\PhysicsCore -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\PhysicsCore\Public -ID:\BuildAgent\work\FNAF9\fnaf9\Intermediate\Build\Win64\fnaf9\Inc\Chaos -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\Experimental -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\Experimental\Chaos\Public -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\Experimental\ChaosCore\Public -ID:\BuildAgent\work\FNAF9\Engine\Source\ThirdParty\Intel -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\Experimental\Voronoi\Public -ID:\BuildAgent\work\FNAF9\Engine\Source\ThirdParty -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\SignalProcessing\Public -ID:\BuildAgent\work\FNAF9\fnaf9\Intermediate\Build\Win64\fnaf9\Inc\AudioExtensions -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\AudioExtensions\Public -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\AudioMixerCore\Public -ID:\BuildAgent\work\FNAF9\fnaf9\Intermediate\Build\Win64\fnaf9\Inc\PropertyAccess -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\PropertyAccess\Public -ID:\BuildAgent\work\FNAF9\fnaf9\Intermediate\Build\Win64\fnaf9\Inc\ClothingSystemRuntimeInterface -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\ClothingSystemRuntimeInterface\Public -ID:\BuildAgent\work\FNAF9\fnaf9\Intermediate\Build\Win64\fnaf9\Inc\AudioMixer -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\AudioMixer\Classes -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\AudioMixer\Public -ID:\BuildAgent\work\FNAF9\Engine\Source\Developer -ID:\BuildAgent\work\FNAF9\Engine\Source\Developer\TargetPlatform\Public -ID:\BuildAgent\work\FNAF9\fnaf9\Intermediate\Build\Win64\fnaf9\Inc\AnimationCore -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\AnimationCore\Public -ID:\BuildAgent\work\FNAF9\fnaf9\Intermediate\Build\Win64\fnaf9\Inc\MoviePlayer -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\MoviePlayer\Public -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\Networking\Public -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\Projects\Public -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\SandboxFile\Public -ID:\BuildAgent\work\FNAF9\fnaf9\Intermediate\Build\Win64\fnaf9\Inc\Serialization -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\Serialization\Public -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\Cbor\Public -ID:\BuildAgent\work\FNAF9\fnaf9\Intermediate\Build\Win64\fnaf9\Inc\Overlay -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\Overlay\Public -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\PreLoadScreen\Public -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\InstallBundleManager\Public -ID:\BuildAgent\work\FNAF9\fnaf9\Intermediate\Build\Win64\fnaf9\Inc\HeadMountedDisplay -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\HeadMountedDisplay\Public -ID:\BuildAgent\work\FNAF9\fnaf9\Intermediate\Build\Win64\fnaf9\Inc\AugmentedReality -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\AugmentedReality\Public -ID:\BuildAgent\work\FNAF9\fnaf9\Intermediate\Build\Win64\fnaf9\Inc\MRMesh -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\MRMesh\Public -ID:\BuildAgent\work\FNAF9\fnaf9\Intermediate\Build\Win64\fnaf9\Inc\MediaUtils -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\MediaUtils\Public -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\Media\Public -ID:\BuildAgent\work\FNAF9\fnaf9\Intermediate\Build\Win64\fnaf9\Inc\ClothingSystemRuntimeNv -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\ClothingSystemRuntimeNv\Public -ID:\BuildAgent\work\FNAF9\fnaf9\Intermediate\Build\Win64\fnaf9\Inc\ClothingSystemRuntimeCommon -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\ClothingSystemRuntimeCommon\Public -ID:\BuildAgent\work\FNAF9\Engine\Source\Developer\AutomationController\Public -ID:\BuildAgent\work\FNAF9\Engine\Source\Developer\TaskGraph\Public -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\SlateNullRenderer\Public -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\SlateRHIRenderer\Public -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\Launch\Public -ID:\BuildAgent\work\FNAF9\Engine\Source\Runtime\SessionServices\Public -ID:\BuildAgent\work\FNAF9\Engine\Source\ThirdParty\PhysX3\PxShared\include -ID:\BuildAgent\work\FNAF9\Engine\Source\ThirdParty\PhysX3\PxShared\include\cudamanager -ID:\BuildAgent\work\FNAF9\Engine\Source\ThirdParty\PhysX3\PxShared\include\filebuf -ID:\BuildAgent\work\FNAF9\Engine\Source\ThirdParty\PhysX3\PxShared\include\foundation -ID:\BuildAgent\work\FNAF9\Engine\Source\ThirdParty\PhysX3\PxShared\include\pvd -ID:\BuildAgent\work\FNAF9\Engine\Source\ThirdParty\PhysX3\PxShared\include\task -ID:\BuildAgent\work\FNAF9\Engine\Source\ThirdParty\PhysX3\PhysX_3.4\Include -ID:\BuildAgent\work\FNAF9\Engine\Source\ThirdParty\PhysX3\PhysX_3.4\Include\cooking -ID:\BuildAgent\work\FNAF9\Engine\Source\ThirdParty\PhysX3\PhysX_3.4\Include\common -ID:\BuildAgent\work\FNAF9\Engine\Source\ThirdParty\PhysX3\PhysX_3.4\Include\extensions -ID:\BuildAgent\work\FNAF9\Engine\Source\ThirdParty\PhysX3\PhysX_3.4\Include\geometry -ID:\BuildAgent\work\FNAF9\Engine\Source\ThirdParty\PhysX3\APEX_1.4\include -ID:\BuildAgent\work\FNAF9\Engine\Source\ThirdParty\PhysX3\APEX_1.4\include\clothing -ID:\BuildAgent\work\FNAF9\Engine\Source\ThirdParty\PhysX3\APEX_1.4\include\nvparameterized -ID:\BuildAgent\work\FNAF9\Engine\Source\ThirdParty\PhysX3\APEX_1.4\include\legacy -ID:\BuildAgent\work\FNAF9\Engine\Source\ThirdParty\PhysX3\APEX_1.4\include\PhysX3 -ID:\BuildAgent\work\FNAF9\Engine\Source\ThirdParty\PhysX3\APEX_1.4\common\include -ID:\BuildAgent\work\FNAF9\Engine\Source\ThirdParty\PhysX3\APEX_1.4\common\include\autogen -ID:\BuildAgent\work\FNAF9\Engine\Source\ThirdParty\PhysX3\APEX_1.4\framework\include -ID:\BuildAgent\work\FNAF9\Engine\Source\ThirdParty\PhysX3\APEX_1.4\framework\include\autogen -ID:\BuildAgent\work\FNAF9\Engine\Source\ThirdParty\PhysX3\APEX_1.4\shared\general\RenderDebug\public -ID:\BuildAgent\work\FNAF9\Engine\Source\ThirdParty\PhysX3\APEX_1.4\shared\general\PairFilter\include -ID:\BuildAgent\work\FNAF9\Engine\Source\ThirdParty\PhysX3\APEX_1.4\shared\internal\include -I"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\INCLUDE" -I"C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.2\include\um" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" -FID:\BuildAgent\work\FNAF9\fnaf9\Intermediate\Build\Win64\fnaf9\Shipping\Engine\SharedPCH.Engine.ShadowErrors.h -YuD:\BuildAgent\work\FNAF9\fnaf9\Intermediate\Build\Win64\fnaf9\Shipping\Engine\SharedPCH.Engine.ShadowErrors.h -FpD:\BuildAgent\work\FNAF9\fnaf9\Intermediate\Build\Win64\fnaf9\Shipping\Engine\SharedPCH.Engine.ShadowErrors.h.pch -FID:\BuildAgent\work\FNAF9\fnaf9\Intermediate\Build\Win64\fnaf9\Shipping\Launch\Definitions.Launch.h -TP -GR- -W4 -showIncludes -X"', src/cpp/module.rs:1211:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`
